<?php
/**
 * OrganizationUserInfoApiApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UMAS API PROD
 *
 * These are UMAS published API availble for third party system consumption.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.47-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * OrganizationUserInfoApiApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrganizationUserInfoApiApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getAllUsersForOrg
     *
     * Retrieve all users which belong to the given organization ID (home org)..
     *
     */
    public function testGetAllUsersForOrg()
    {
    }

    /**
     * Test case for getGivenOrgInfo
     *
     * Retrieve organization information for the given organization ID..
     *
     */
    public function testGetGivenOrgInfo()
    {
    }

    /**
     * Test case for getUserOrginfo
     *
     * Retrieve user and correspondng org info. The ids must match, i.e. the organization with the given organizationId MUST be the users home org with the given userId..
     *
     */
    public function testGetUserOrginfo()
    {
    }
}
