<?php
/**
 * OrganisationInfoDTOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UMAS API PROD
 *
 * These are UMAS published API availble for third party system consumption.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.47-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * OrganisationInfoDTOTest Class Doc Comment
 *
 * @category    Class
 * @description OrganisationInfoDTO
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrganisationInfoDTOTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "OrganisationInfoDTO"
     */
    public function testOrganisationInfoDTO()
    {
    }

    /**
     * Test attribute "organization_id"
     */
    public function testPropertyOrganizationId()
    {
    }

    /**
     * Test attribute "gs_id"
     */
    public function testPropertyGsId()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "tax_no"
     */
    public function testPropertyTaxNo()
    {
    }

    /**
     * Test attribute "main_address"
     */
    public function testPropertyMainAddress()
    {
    }

    /**
     * Test attribute "website"
     */
    public function testPropertyWebsite()
    {
    }

    /**
     * Test attribute "company_email"
     */
    public function testPropertyCompanyEmail()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "trust_level"
     */
    public function testPropertyTrustLevel()
    {
    }

    /**
     * Test attribute "business_partner"
     */
    public function testPropertyBusinessPartner()
    {
    }

    /**
     * Test attribute "translated_name"
     */
    public function testPropertyTranslatedName()
    {
    }

    /**
     * Test attribute "delivery_addresses"
     */
    public function testPropertyDeliveryAddresses()
    {
    }
}
